[package]
name = "blog-axum-app"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
tokio = { version = "1.49.0", features = ["full"] }
serde = "1.0.228"
serde_json = "1.0"
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite", "tls-native-tls" ] }
secrecy = "0.10.3"
